# This workflow will upload epix to PyPi using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PyPI

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # Setup steps
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: python -m pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
